"""Recorded test — 2026-09-11. Auto-generated by make record."""

import pytest

pytestmark = [pytest.mark.web, pytest.mark.recorded]

import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://ai-mfg-demo.authentication.us20.hana.ondemand.com/login")
    page.get_by_role("link", name="Default Identity Provider").click()
    page.get_by_role("textbox", name="E-Mail, User ID or Login Name").click()
    page.get_by_role("textbox", name="E-Mail, User ID or Login Name").fill("neeraj.kumar@twenty5.com")
    page.get_by_role("button", name="Continue").click()
    page.get_by_role("button", name="Show Password").click()
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("<enter your password>")
    page.get_by_role("button", name="Continue").click()
    page.goto("https://twenty5ipe-ai-mfg.cfapps.us20.hana.ondemand.com/")
