#!/usr/bin/env python3
"""Record a browser test using Playwright codegen.

Usage (via Makefile):
    make record-ipe NAME=create_estimate           # record against IPE
    make record-url NAME=my_test URL=https://...   # record against any URL

What happens:
    1. A browser opens with the Playwright Inspector sidebar.
    2. You interact with the page — every click, type, and assertion is captured.
    3. When you close the Inspector, the test is saved to tests/recorded/.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def post_process(file_path: Path) -> None:
    content = file_path.read_text()
    if not content.strip():
        return

    header = (
        f'"""Recorded test — {date.today().isoformat()}. Auto-generated by make record."""\n'
        "\n"
        "import pytest\n"
        "\n"
        "pytestmark = [pytest.mark.web, pytest.mark.recorded]\n"
        "\n"
    )
    content = header + content
    file_path.write_text(content)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Record a browser test with Playwright codegen"
    )
    parser.add_argument("name", help="Test name (e.g. create_estimate)")
    parser.add_argument("--url", required=True, help="URL to record against")
    args = parser.parse_args()

    name = re.sub(r"[^a-z0-9_]", "_", args.name.lower())
    if not name.startswith("test_"):
        name = f"test_{name}"

    output_dir = PROJECT_ROOT / "tests" / "recorded"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / f"{name}.py"

    if output_file.exists():
        print(f"\n  WARNING: {output_file.name} already exists and will be overwritten.\n")

    print(f"\n  Recording against: {args.url}")
    print(f"  Output file:       tests/recorded/{name}.py")
    print()
    print("  ┌─────────────────────────────────────────────────────┐")
    print("  │  A browser will open with the Playwright Inspector. │")
    print("  │  Interact with the page — your actions are recorded.│")
    print("  │  Close the Inspector window when you're done.       │")
    print("  └─────────────────────────────────────────────────────┘")
    print()

    subprocess.run(
        [
            sys.executable,
            "-m",
            "playwright",
            "codegen",
            "--target",
            "python-pytest",
            "--output",
            str(output_file),
            args.url,
        ],
        cwd=str(PROJECT_ROOT),
    )

    if output_file.exists() and output_file.stat().st_size > 0:
        post_process(output_file)
        print(f"\n  Test saved: tests/recorded/{name}.py")
        print(f"  Replay it:  make play NAME={args.name}")
        print()
    else:
        print("\n  No test was recorded (file is empty or codegen was cancelled).\n")


if __name__ == "__main__":
    main()
